apiVersion: v2
name: postgresql
description: A Helm chart for PostgreSQL Enterprise Grade with Replication
type: application
version: 1.0.0
appVersion: "16.2.0"
keywords:
  - postgresql
  - database
  - postgres
home: https://www.postgresql.org
maintainers:
  - name: API Gateway Team
    email: api-gateway@example.com
