global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'apisix'
    static_configs:
      - targets:
          - 'apisix-0:9091'
          - 'apisix-1:9091'
          - 'apisix-2:9091'
        labels:
          service: 'apisix-gateway'
    scrape_interval: 10s
    metrics_path: '/apisix/prometheus/metrics'

  - job_name: 'nacos'
    static_configs:
      - targets:
          - 'nacos-0:8848'
          - 'nacos-1:8848'
          - 'nacos-2:8848'
        labels:
          service: 'nacos-config'
    scrape_interval: 30s
    metrics_path: '/nacos/actuator/prometheus'

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  - job_name: 'postgresql'
    static_configs:
      - targets: ['postgresql-primary:9187', 'postgresql-read-0:9187', 'postgresql-read-1:9187']
    scrape_interval: 30s

  - job_name: 'redis'
    static_configs:
      - targets:
          - 'redis-0:9121'
          - 'redis-1:9121'
          - 'redis-2:9121'
          - 'redis-3:9121'
          - 'redis-4:9121'
          - 'redis-5:9121'
    scrape_interval: 30s

  - job_name: 'skywalking-oap'
    static_configs:
      - targets: ['skywalking-oap:1234']
    scrape_interval: 30s
