apiVersion: v2
name: redis
description: A Helm chart for Redis Cluster Enterprise Grade
type: application
version: 1.0.0
appVersion: "7.2.4"
keywords:
  - redis
  - cache
  - in-memory
home: https://redis.io
maintainers:
  - name: API Gateway Team
    email: api-gateway@example.com
